


@host =doctor-c5302a2d9454.herokuapp.com
# @host = localhost:5001
@token =Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InVzZXJuYW1lIjoiaGVsbG8iLCJlbWFpbCI6InNhamphZEBuYXNtaXMuY29tIiwiaWQiOiI2NThmMDNiYzMwMTI4OGRjZDMwZTE1YjMiLCJ0eXBlIjoidXNlciIsImRhdGEiOnsidHlwZSI6InVzZXIifX0sImlhdCI6MTcwMzg3MTQyMSwiZXhwIjoxNzM0OTc1NDIxfQ.Nc7OSmsZaWw3lgGdzb-lz--E_pXe97hBeujjF3ZmqYs

### Doctor Profile Creation


POST /api/v1/doctors HTTP/1.1
Host: {{host}}
Content-Type: application/json
Authorization: {{token}}
 
{
    "name": "Dr. John Doe",
    "img": "https://example.com/doctor_image.jpg",
    "rating": 4.5,
    "degree": "MD",
    "location": "City Hospital",
    "availableDate": ["Monday", "Wednesday", "Friday"],
    "availableTime": ["09:00", "14:00"]
}


### Get All Doctor Profiles

GET /api/v1/doctors HTTP/1.1
Host: {{host}}
Authorization:{{token}}





### Get a Single Doctor Profile
 

GET /api/v1/doctors/658f03bc301288dcd30e15b3 HTTP/1.1
Host: {{host}}
Authorization:{{token}}



### Update Doctor Profile

 

PUT /api/v1/doctors HTTP/1.1
Host: {{host}}
Content-Type: application/json
Authorization:{{token}}

{
    "name": "Dr. sajjad",
    "img": "https://example.com/updated_doctor_image.jpg",
    "rating": 4.8,
    "degree": "PhD",
    "location": "New Hospital",
    "availableDate": ["Tuesday", "Thursday", "Saturday"],
    "availableTime": ["10:00", "15:00"]
}

### Delete Doctor Profile

 

DELETE /api/v1/doctors/ HTTP/1.1
Host: {{host}}
Authorization:{{token}}


